{ :en => {

    :google_adwords_languages => {
      :ar    => "Arabic",
      :bg    => "Bulgarian",
      :ca    => "Catalan",
      :zh_CN => "Chinese (simplified)",
      :zh_TW => "Chinese (traditional)",
      :hr    => "Croatian",
      :cs    => "Czech",
      :da    => "Danish",
      :nl    => "Dutch",
      :en    => "English",
      :et    => "Estonian",
      :tl    => "Filipino",
      :fi    => "Finnish",
      :fr    => "French",
      :de    => "German",
      :el    => "Greek",
      :iw    => "Hebrew",
      :hi    => "Hindi",
      :hu    => "Hungarian",
      :is    => "Icelandic",
      :id    => "Indonesian",
      :it    => "Italian",
      :ja    => "Japanese",
      :ko    => "Korean",
      :lv    => "Latvian",
      :lt    => "Lithuanian",
      :no    => "Norwegian",
      :pl    => "Polish",
      :pt    => "Portuguese",
      :ro    => "Romanian",
      :ru    => "Russian",
      :sr    => "Serbian",
      :sk    => "Slovak",
      :sl    => "Slovenian",
      :es    => "Spanish",
      :sv    => "Swedish",
      :th    => "Thai",
      :tr    => "Turkish",
      :uk    => "Ukrainian",
      :ur    => "Urdu",
      :vi    => "Vietnamese"
    }

}}